site_name: Pemrograman Berorientasi Objek

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - py
    - csharp
    - java
    - vbnet
    - kotlin

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugin:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

edit_uri: ""

nav:
  - Home: 'index.md'
  - "01. Konsep Pemrograman Berorientasi Objek" : "01_konsep_pemrograman_berorientasi_objek.md"
  - "02. Praktik Pendekatan PBO" : "02_praktik_pendekatan_pbo.md"
  - "03. Variable Tipe Data" : "03.1_tipe_data.md"
  - "04. Operator Kondisi" : "04_conditional.md"
  - "05. Operator Perulangan" : "05_loops.md"
  - "06. Tipe data Himpunan / Array" : 
    - '06.1. Array : Intro' : "06_array_list.md"
    - '06.2. Array' : "array/array_1.md"
  - "07. Konsep Pemodelan" : "07_konsep_pemodelan.md"
  - "08." : "08_konsep_pemodelan.md"
  - "09." : "09_konsep_pemodelan.md"
  - "10. Penanganan Error" : "10_error_handling.md"
  - "11. Multi Threading" : "11_multithreading.md"
  - "12. Input dan Output I/O" : "12_io.md"
  - "13. Enkripsi" : "13_enkripsi_tradisional.md"
  - "14. GUI Basic" : "14_gui_basic.md"
  - "15. GUI Database" : "15_gui_database.md"